create table #tmp (id int, parent int, name nvarchar(255), description nvarchar(1000))

insert into #tmp values
(1, null, 'Chapter I', 'General provisions'),
(2, 1, 'Section 1', 'General provisions'),
(3, null, 'Chapter II', 'Principles'),
(4, 3, 'Section 1', 'Principles'),
(5, null, 'Chapter III', 'Rights of the data subject'),
(6, 5, 'Section 1', 'Transparency and modalities'),
(7, 5, 'Section 2', 'Information and access to personal data'),
(8, 5, 'Section 3', 'Rectification and erasure'),
(9, 5, 'Section 4', 'Right to object and automated individual decision-making'),
(10, 5, 'Section 5', 'Restrictions'),
(11, null, 'Chapter IV', 'Controller and processor'),
(12, 11, 'Section 1', 'General obligations'),
(13, 11, 'Section 2', 'Security of personal data'),
(14, 11, 'Section 3', 'Data protection impact assessment and prior consultation'),
(15, 11, 'Section 4', 'Data protection officer'),
(16, 11, 'Section 5', 'Codes of conduct and certification'),
(17, null, 'Chapter V', 'Transfers of personal data to third countries or international organisations'),
(18, 17, 'Section 1', 'Transfers of personal data to third countries or international organisations'),
(19, null, 'Chapter VI', 'Independent supervisory authorities'),
(20, 19, 'Section 1', 'Independent status'),
(21, 19, 'Section 2', 'Competence, tasks and powers'),
(22, null, 'Chapter VII', 'Cooperation and consistency'),
(23, 22, 'Section 1', 'Cooperation'),
(24, 22, 'Section 2', 'Consistency'),
(25, 22, 'Section 3', 'European data protection board'),
(26, null, 'Chapter VIII', 'Remedies, liability and penalties'),
(27, 26, 'Section 1', 'Remedies, liability and penalties'),
(28, null, 'Chapter IX', 'Provisions relating to specific processing situations'),
(29, 28, 'Section 1', 'Provisions relating to specific processing situations'),
(30, null, 'Chapter X', 'Delegated acts and implementing acts'),
(31, 30, 'Section 1', 'Delegated acts and implementing acts'),
(32, null, 'Chapter XI', 'Final provisions'),
(33, 33, 'Section 1', 'Final provisions'),
(34, 2, 'Article 1', 'Subject-matter and objectives'),
(35, 2, 'Article 2', 'Material scope'),
(36, 2, 'Article 3', 'Territorial scope'),
(37, 2, 'Article 4', 'Definitions'),
(38, 4, 'Article 5', 'Principles relating to processing of personal data'),
(39, 4, 'Article 6', 'Lawfulness of processing'),
(40, 4, 'Article 7', 'Conditions for consent'),
(41, 4, 'Article 8', 'Conditions applicable to child''s consent in relation to information society services'),
(42, 4, 'Article 9', 'Processing of special categories of personal data'),
(43, 4, 'Article 10', 'Processing of personal data relating to criminal convictions and offences'),
(44, 4, 'Article 11', 'Processing which does not require identification'),
(45, 6, 'Article 12', 'Transparent information, communication and modalities for the exercise of the rights of the data subject'),
(46, 7, 'Article 13', 'Information to be provided where personal data are collected from the data subject '),
(47, 7, 'Article 14', 'Information to be provided where personal data have not been obtained from the data subject'),
(48, 7, 'Article 15', 'Right of access by the data subject'),
(49, 8, 'Article 16', 'Right to rectification'),
(50, 8, 'Article 17', 'Right to erasure (''right to be forgotten'')'),
(51, 8, 'Article 18', 'Right to restriction of processing'),
(52, 8, 'Article 19', 'Notification obligation regarding rectification or erasure of personal data or restriction of processing'),
(53, 8, 'Article 20', 'Right to data portability'),
(54, 9, 'Article 21', 'Right to object'),
(55, 9, 'Article 22', 'Automated individual decision-making, including profiling'),
(56, 10, 'Article 23', 'Restrictions'),
(57, 12, 'Article 24', 'Responsibility of the controller'),
(58, 12, 'Article 25', 'Data protection by design and by default'),
(59, 12, 'Article 26', 'Article 26 - Joint controllers'),
(60, 12, 'Article 27', 'Representatives of controllers or processors not established in the Union'),
(61, 12, 'Article 28', 'Processor'),
(62, 12, 'Article 29', 'Processing under the authority of the controller or processor'),
(63, 12, 'Article 30', 'Records of processing activities'),
(64, 12, 'Article 31', 'Cooperation with the supervisory authority'),
(65, 13, 'Article 32', 'Security of processing'),
(66, 13, 'Article 33', 'Notification of a personal data breach to the supervisory authority'),
(67, 13, 'Article 34', 'Communication of a personal data breach to the data subject'),
(68, 14, 'Article 35', 'Data protection impact assessment'),
(69, 14, 'Article 36', 'Prior consultation'),
(70, 15, 'Article 37', 'Designation of the data protection officer'),
(71, 15, 'Article 38', 'Position of the data protection officer'),
(72, 15, 'Article 39', 'Tasks of the data protection officer'),
(73, 16, 'Article 40', 'Codes of conduct'),
(74, 16, 'Article 41', 'Monitoring of approved codes of conduct'),
(75, 16, 'Article 42', 'Certification'),
(76, 16, 'Article 43', 'Certification bodies'),
(77, 18, 'Article 44', 'General principle for transfers'),
(78, 18, 'Article 45', 'Transfers on the basis of an adequacy decision'),
(79, 18, 'Article 46', 'Transfers subject to appropriate safeguards'),
(80, 18, 'Article 47', 'Binding corporate rules'),
(81, 18, 'Article 48', 'Transfers or disclosures not authorised by Union law'),
(82, 18, 'Article 49', 'Derogations for specific situations'),
(83, 18, 'Article 50', 'International cooperation for the protection of personal data'),
(84, 20, 'Article 51', 'Supervisory authority'),
(85, 20, 'Article 52', 'Independence'),
(86, 20, 'Article 53', 'General conditions for the members of the supervisory authority '),
(87, 20, 'Article 54', 'Rules on the establishment of the supervisory authority'),
(88, 21, 'Article 55', 'Competence'),
(89, 21, 'Article 56', 'Competence of the lead supervisory authority'),
(90, 21, 'Article 57', 'Tasks'),
(91, 21, 'Article 58', 'Powers'),
(92, 21, 'Article 59', 'Activity reports'),
(93, 23, 'Article 60', 'Cooperation between the lead supervisory authority and the other supervisory authorities concerned'),
(94, 23, 'Article 61', 'Mutual assistance'),
(95, 23, 'Article 62', 'Joint operations of supervisory authorities'),
(96, 24, 'Article 63', 'Consistency mechanism'),
(97, 24, 'Article 64', 'Opinion of the Board'),
(98, 24, 'Article 65', 'Dispute resolution by the Board'),
(99, 24, 'Article 66', 'Urgency procedure'),
(100, 24, 'Article 67', 'Exchange of information'),
(101, 25, 'Article 68', 'European Data Protection Board'),
(102, 25, 'Article 69', 'Independence'),
(103, 25, 'Article 70', 'Tasks of the Board'),
(104, 25, 'Article 71', 'Reports'),
(105, 25, 'Article 72', 'Procedure'),
(106, 25, 'Article 73', 'Chair'),
(107, 25, 'Article 74', 'Tasks of the Chair'),
(108, 25, 'Article 75', 'Secretariat'),
(109, 25, 'Article 76', 'Confidentiality'),
(110, 27, 'Article 77', 'Right to lodge a complaint with a supervisory authority'),
(111, 27, 'Article 78', 'Right to an effective judicial remedy against a supervisory authority'),
(112, 27, 'Article 79', 'Right to an effective judicial remedy against a controller or processor'),
(113, 27, 'Article 80', 'Representation of data subjects'),
(114, 27, 'Article 81', 'Suspension of proceedings'),
(115, 27, 'Article 82', 'Right to compensation and liability'),
(116, 27, 'Article 83', 'General conditions for imposing administrative fines'),
(117, 29, 'Article 84', 'Penalties'),
(118, 29, 'Article 85', 'Processing and freedom of expression and information'),
(119, 29, 'Article 86', 'Processing and public access to official documents'),
(120, 29, 'Article 87', 'Processing of the national identification number'),
(121, 29, 'Article 88', 'Processing in the context of employment'),
(122, 29, 'Article 89', 'Safeguards and derogations relating to processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes'),
(123, 29, 'Article 90', 'Obligations of secrecy'),
(124, 29, 'Article 91', 'Existing data protection rules of churches and religious associations'),
(125, 31, 'Article 92', 'Exercise of the delegation'),
(126, 31, 'Article 93', 'Committee procedure'),
(127, 33, 'Article 94', 'Repeal of Directive'),
(128, 33, 'Article 95', 'Relationship with Directive 2002/58/EC'),
(129, 33, 'Article 96', 'Relationship with previously concluded Agreements'),
(130, 33, 'Article 97', ' Commission reports'),
(131, 33, 'Article 98', 'Review of other Union legal acts on data protection'),
(132, 33, 'Article 99', 'Entry into force and application')

--select * from #tmp

declare @lastId int
declare @firstId int
select @firstId=min(id) from #tmp
select @lastId =IDENT_CURRENT('SoaChapter')

update t set t.id=id-@firstId+1+@lastId,t.Parent =Parent-@firstId+1+@lastId from #tmp as t

insert into SoaChapter (SoaType)
	select 5 from #tmp
update sc set sc.Parent=t.parent
from
#tmp t
join SoaChapter sc on t.id=sc.id

insert into SoaChapterItems (SoaChapterId, IsoCode, Name, Description, Goal, HowTo, Info)
select id, 'nb-no', name, description, '', '', '' from #tmp

insert into SoaChapterItems (SoaChapterId, IsoCode, Name, Description, Goal, HowTo, Info)
select id, 'en-us', name, description, '', '', '' from #tmp

drop table #tmp