//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetThreat_Attributes
    {
        public int AssetThreatAttributeId { get; set; }
        public int AttributeId { get; set; }
        public int AssetThreatId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AttributeTypeId { get; set; }
        public int AttributeCategoryId { get; set; }
        public string Comment { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> MonthTimeframe { get; set; }
        public Nullable<int> DayTimeframe { get; set; }
        public Nullable<int> HourTimeframe { get; set; }
        public Nullable<int> Source { get; set; }
    
        public virtual Asset_Threat Asset_Threat { get; set; }
        public virtual AttributeCategory AttributeCategory { get; set; }
        public virtual Attribute Attribute { get; set; }
        public virtual AttributeType AttributeType { get; set; }
    }
}
