//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeLink
    {
        public int AttributeLinkId { get; set; }
        public int ParentAttributeId { get; set; }
        public int AttributeId { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Attribute Attribute1 { get; set; }
    }
}
