//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attribute()
        {
            this.AssetThreat_Attributes = new HashSet<AssetThreat_Attributes>();
            this.AttributeLinks = new HashSet<AttributeLink>();
            this.AttributeLinks1 = new HashSet<AttributeLink>();
            this.Threats = new HashSet<Threat>();
        }
    
        public int AttributeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string AttributeTypeId { get; set; }
        public int AttributeCategoryId { get; set; }
        public string Comment { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> MonthTimeframe { get; set; }
        public Nullable<int> DayTimeframe { get; set; }
        public Nullable<int> HourTimeframe { get; set; }
        public Nullable<int> Source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetThreat_Attributes> AssetThreat_Attributes { get; set; }
        public virtual AttributeCategory AttributeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeLink> AttributeLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttributeLink> AttributeLinks1 { get; set; }
        public virtual AttributeType AttributeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Threat> Threats { get; set; }
    }
}
