//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessContinuityPlan
    {
        public int BusinessContinuityPlanId { get; set; }
        public string Text { get; set; }
        public Nullable<int> AssetId { get; set; }
        public int Revision { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> ProcessId { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
