//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HtmlComment
    {
        public int HtmlCommentId { get; set; }
        public string Text { get; set; }
        public Nullable<int> AssetThreatId { get; set; }
        public Nullable<int> AssetThreatControlId { get; set; }
        public Nullable<int> AssetId { get; set; }
        public int Revision { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> ThreatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ControlId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Asset_Threat Asset_Threat { get; set; }
        public virtual AssetThreat_Control AssetThreat_Control { get; set; }
        public virtual Process Process { get; set; }
        public virtual Threat Threat { get; set; }
        public virtual Control Control { get; set; }
    }
}
