//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RAAPEntities : DbContext
    {
        public RAAPEntities()
            : base("name=RAAPEntities")
        {
        }
    
        public RAAPEntities(string connectionString) : base(connectionString){    }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<Asset_Asset> Asset_Asset { get; set; }
        public virtual DbSet<Asset_Threat> Asset_Threat { get; set; }
        public virtual DbSet<AssetSubCategory> AssetSubCategories { get; set; }
        public virtual DbSet<AssetThreat_Attributes> AssetThreat_Attributes { get; set; }
        public virtual DbSet<AssetThreat_Control> AssetThreat_Control { get; set; }
        public virtual DbSet<AttributeCategory> AttributeCategories { get; set; }
        public virtual DbSet<AttributeLink> AttributeLinks { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttributeType> AttributeTypes { get; set; }
        public virtual DbSet<BusinessContinuityPlan> BusinessContinuityPlans { get; set; }
        public virtual DbSet<Consequence> Consequences { get; set; }
        public virtual DbSet<Control> Controls { get; set; }
        public virtual DbSet<ControlCategory> ControlCategories { get; set; }
        public virtual DbSet<ControlRisk> ControlRisks { get; set; }
        public virtual DbSet<CriticalityCategory> CriticalityCategories { get; set; }
        public virtual DbSet<DowntimeEffect> DowntimeEffects { get; set; }
        public virtual DbSet<HtmlComment> HtmlComments { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessCategory> ProcessCategories { get; set; }
        public virtual DbSet<Risk> Risks { get; set; }
        public virtual DbSet<RiskParameter> RiskParameters { get; set; }
        public virtual DbSet<RiskType> RiskTypes { get; set; }
        public virtual DbSet<Soa> Soas { get; set; }
        public virtual DbSet<SoaFile> SoaFiles { get; set; }
        public virtual DbSet<SoaLink> SoaLinks { get; set; }
        public virtual DbSet<Threat> Threats { get; set; }
        public virtual DbSet<ThreatCategory> ThreatCategories { get; set; }
        public virtual DbSet<ThreatRisk> ThreatRisks { get; set; }
        public virtual DbSet<ThreatSource> ThreatSources { get; set; }
        public virtual DbSet<TimeCost> TimeCosts { get; set; }
        public virtual DbSet<Vulnerability> Vulnerabilities { get; set; }
        public virtual DbSet<VulnerabilityCatalog> VulnerabilityCatalogs { get; set; }
        public virtual DbSet<Asset_SoaChapter> Asset_SoaChapter { get; set; }
        public virtual DbSet<SoaSetting> SoaSettings { get; set; }
    }
}
