//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Risk()
        {
            this.RiskParameters = new HashSet<RiskParameter>();
        }
    
        public int RiskId { get; set; }
        public int DamageIsoRisk { get; set; }
        public int FinancialIsoRisk { get; set; }
        public int ReputationIsoRisk { get; set; }
        public int DamageNsRisk { get; set; }
        public int FinancialNsRisk { get; set; }
        public int ReputationNsRisk { get; set; }
        public Nullable<int> AssetThreatId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> AssetId { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Asset_Threat Asset_Threat { get; set; }
        public virtual Process Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskParameter> RiskParameters { get; set; }
    }
}
