//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoaFile
    {
        public int FileId { get; set; }
        public string FileName { get; set; }
        public int SoaChapterId { get; set; }
        public System.Guid Guid { get; set; }
    }
}
