//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoaLink
    {
        public int SoaLinkId { get; set; }
        public string URL { get; set; }
        public string Name { get; set; }
        public int SoaId { get; set; }
    
        public virtual Soa Soa { get; set; }
    }
}
