//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Threat()
        {
            this.Asset_Threat = new HashSet<Asset_Threat>();
            this.HtmlComments = new HashSet<HtmlComment>();
            this.ThreatRisks = new HashSet<ThreatRisk>();
            this.Attributes = new HashSet<Attribute>();
            this.Controls = new HashSet<Control>();
        }
    
        public int ThreatId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int DamageProbability { get; set; }
        public int DamageImpact { get; set; }
        public int ThreatCategoryId { get; set; }
        public int InternalExternal { get; set; }
        public int SecuritySafety { get; set; }
        public int RiskAssessmentMethod { get; set; }
        public bool AcceptRisk { get; set; }
        public bool Confidenciality { get; set; }
        public bool Integrity { get; set; }
        public bool Availability { get; set; }
        public bool ReduceRisk { get; set; }
        public int ReputationProbability { get; set; }
        public int ReputationImpact { get; set; }
        public int FinancialProbability { get; set; }
        public int FinancialImpact { get; set; }
        public int DamageValue { get; set; }
        public int DamageThreat { get; set; }
        public int DamageVulnerability { get; set; }
        public int FinancialValue { get; set; }
        public int FinancialThreat { get; set; }
        public int FinancialVulnerability { get; set; }
        public int ReputationValue { get; set; }
        public int ReputationThreat { get; set; }
        public int ReputationVulnerability { get; set; }
        public bool ShareRisk { get; set; }
        public bool AvoidRisk { get; set; }
        public Nullable<System.DateTime> RiskDate { get; set; }
        public string RiskUser { get; set; }
        public bool Authenticity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset_Threat> Asset_Threat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HtmlComment> HtmlComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThreatRisk> ThreatRisks { get; set; }
        public virtual ThreatCategory ThreatCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attribute> Attributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Control> Controls { get; set; }
    }
}
