//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAAP.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeCost
    {
        public int TimeCostId { get; set; }
        public int Time { get; set; }
        public decimal Cost { get; set; }
        public int AssetId { get; set; }
    
        public virtual Asset Asset { get; set; }
    }
}
